# Project: xc-predictor
# File:    tfrrs/fetch/fetch_tf.py
# Purpose: Fetch a TFRRS results page's raw HTML, via an escalating ladder that
#          spends the least effort that works:
#            tier 1  requests.get        (cheap, no browser)
#            tier 2  curl_cffi           (Chrome TLS fingerprint — defeats most
#                                         fingerprint blocks, still no browser)
#            tier 3  Playwright in-page  (heavy; only if a live page is supplied)
#          Mirrors the project's anet fast-path-with-fallback philosophy
#          (getAllResultsTF) and reuses the same exception TYPES so a launcher
#          can catch blocks uniformly across both sources.
#
#          KEY DIFFERENCE FROM anet: anet expects JSON, so "got HTML" = blocked.
#          TFRRS expects HTML (the results page IS html), so the failure signal
#          is content-based: did we get the RESULTS page, or a CHALLENGE page?
#          That distinction (not the status code) drives tier escalation.
 
import requests
from curl_cffi import requests as curl_requests   # Chrome-impersonating HTTP
import sys
import asyncio

sys.path.insert(0, "scripts")
from scraper import CloudflareException, RateLimitException

# Raised when the EXIT IP is blocked at the CDN edge (CloudFront 403). The
# session loop catches this specifically and triggers an immediate rotation,
# rather than escalating tiers (which won't help — every tier shares the IP).
class IPBlockedException(Exception):
    pass

# Markers that identify a REAL TFRRS results page. These are the structural
# anchors our parsers rely on (the result tables + the meet title panel), so if
# they're present we know we got the page we wanted — not a challenge stand-in.
_RESULTS_MARKERS = ("tablesaw", "panel-title")
 
# Markers that identify a Cloudflare / bot-challenge interstitial. Any of these
# means the body is a block page, no matter what HTTP status came with it.
_BLOCK_MARKERS = (
    "Just a moment",        # Cloudflare's "checking your browser" page title
    "cf-challenge",         # challenge container id/class
    "__cf_chl",             # challenge script token
    "Attention Required",   # Cloudflare 1020/block heading
    "cf-browser-verification",
)

# Markers identifying a CloudFront IP-level block (a 403 "Request blocked").
# DISTINCT from Cloudflare's per-session challenge: this means the EXIT IP is
# burned at the CDN edge under aggregate load -> the fix is rotate the IP, not
# back off one session. Detected separately so the loop can react differently.
_CLOUDFRONT_BLOCK_MARKERS = (
    "Generated by cloudfront",
    "Request blocked",
    "The request could not be satisfied",
)


# _looksLikeCloudFrontBlock
# Purpose: True if the body is a CloudFront IP-level 403 block page.
# Arguments:
#           html: the response body text.
# Output:   True if any CloudFront block marker is present.
def _looksLikeCloudFrontBlock(html):
    return any(marker in html for marker in _CLOUDFRONT_BLOCK_MARKERS)



# _looksLikeBlock
# Purpose: True if the HTML is a Cloudflare/bot challenge interstitial rather
#          than real content. Checked first, because a block page can still be
#          short HTML that happens to lack our results markers.
# Arguments:
#           html: the response body text.
# Output:   True if any block marker is present.
def _looksLikeBlock(html):
    return any(marker in html for marker in _BLOCK_MARKERS)
 
 
# _looksLikeResultsPage
# Purpose: True if the HTML carries the structural anchors our parsers need
#          (a result table + the meet title panel). This is the positive
#          confirmation that a tier actually delivered the page — not just
#          "didn't obviously fail."
# Arguments:
#           html: the response body text.
# Output:   True if the page looks like a parseable TFRRS results page.
def _looksLikeResultsPage(html):
    # Require BOTH markers: a stray "tablesaw" or "panel-title" in a block page's
    # boilerplate shouldn't pass us a junk body. A real results page has both.
    return all(marker in html for marker in _RESULTS_MARKERS)
 
 
# _classifyResponse
# Purpose: Turn a (status, html) pair into one verdict the ladder acts on, so
#          every tier shares ONE definition of success/failure instead of each
#          re-deciding. Order matters: 429 first (a specific recoverable signal),
#          then explicit block, then positive results confirmation.
# Arguments:
#           status: HTTP status code (int), or None if the tier can't report one.
#           html:   the response body text (may be "").
# Output:   one of the strings "ok" | "block" | "rate_limit" | "empty" | "unknown".
def _classifyResponse(status, html):
    if status == 429:
        return "rate_limit"
    if not html:
        return "empty"
    # CloudFront IP-block first — it's the "rotate the IP NOW" signal, distinct
    # from a Cloudflare challenge. A 403 status OR the body markers catch it.
    if status == 403 or _looksLikeCloudFrontBlock(html):
        return "ip_blocked"
    if _looksLikeBlock(html):
        return "block"
    if _looksLikeResultsPage(html):
        return "ok"
    return "unknown"


# ------------------------------------------------------------------ #
# TIERS — each does ONE fetch method and returns (status, html).
# None status means "the tier couldn't run / threw"; the ladder treats
# that as a failure and escalates.
# ------------------------------------------------------------------ #


# A realistic browser User-Agent. Tier 1 (plain requests) sends no browser
# fingerprint, but a real UA string still avoids the laziest UA-only blocks.
_UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
       "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
 
# Per-request timeout (seconds). Generous like the anet 15s budget; a real
# TFRRS page returns fast, so this only guards against a hung connection.
_TIMEOUT = 20

# _tierRequests
# Purpose: Tier 1 — a plain requests.get. Cheapest path; works if TFRRS serves
#          the page without a fingerprint challenge.
# Arguments:
#           url: the TFRRS results page URL.
# Output:   (status, html). On any transport error, (None, "") so the ladder
#           escalates instead of crashing.
def _tierRequests(url):
    try:
        resp = requests.get(url, headers={"User-Agent": _UA}, timeout=_TIMEOUT)
        return resp.status_code, resp.text
    except requests.RequestException:
        # DNS/connection/timeout — let the next tier try.
        return None, ""
    
# _tierCurlCffi
# Purpose: Tier 2 — curl_cffi impersonating Chrome. Sends a real Chrome TLS
#          fingerprint, defeating fingerprint-based blocks that stop tier 1
#          without needing a full browser.
# Arguments:
#           url: the TFRRS results page URL.
# Output:   (status, html), or (None, "") on transport error.
def _tierCurlCffi(url):
    try:
        # impersonate="chrome" makes the TLS/JA3 handshake look like real Chrome.
        resp = curl_requests.get(url, impersonate="chrome", timeout=_TIMEOUT)
        return resp.status_code, resp.text
    except Exception:
        # curl_cffi raises its own error types; any failure -> escalate.
        return None, ""
    
# _tierPlaywright
# Purpose: Tier 3 — fetch the page's HTML from inside a live Playwright page,
#          inheriting its cookies/Cloudflare clearance (the anet model). Only
#          runs if the caller supplied a page; otherwise the ladder is out of
#          tiers. This is ASYNC because Playwright's API is — see fetchTFPage's
#          handling.
# Arguments:
#           page: a Playwright async page object, already on athletic-cleared
#                 session (or at least a real browser), or None.
#           url:  the TFRRS results page URL.
# Output:   coroutine resolving to (status, html), or (None, "") if no page.
async def _tierPlaywright(page, url):
    if page is None:
        return None, ""
    try:
        # page.goto loads the URL in the real browser; .content() returns the
        # rendered HTML after any Cloudflare JS challenge has resolved.
        response = await page.goto(url, timeout=_TIMEOUT * 1000)
        html = await page.content()
        status = response.status if response is not None else None
        return status, html
    except Exception:
        return None, ""
    

# ------------------------------------------------------------------ #
# ORCHESTRATOR
# ------------------------------------------------------------------ #


# _handleVerdict
# Purpose: Given a tier's (status, html) verdict, decide the ladder's action:
#          return the html (success), raise (rate limit — a distinct signal the
#          caller may want to back off on), or signal "escalate" (None) so the
#          orchestrator tries the next tier. Centralises the decision so all
#          three tiers are judged identically.
# Arguments:
#           status, html: the tier's raw result.
# Output:   the html string on success; None to mean "escalate to next tier".
#           Raises RateLimitException on a 429.
def _handleVerdict(status, html):
    verdict = _classifyResponse(status, html)
    if verdict == "ok":
        return html
    if verdict == "rate_limit":
        raise RateLimitException("TFRRS returned 429 (rate limited)")
    if verdict == "ip_blocked":
        # IP burned at the CDN edge — escalating tiers won't help (same IP).
        # Raise so the session loop rotates immediately.
        raise IPBlockedException("TFRRS: CloudFront IP block (403)")
    return None

# fetchTFPage
# Purpose: Fetch a TFRRS results page's HTML via the escalating ladder. Returns
#          the raw HTML of a confirmed results page, or raises if every tier was
#          blocked. SYNC: tiers 1-2 are plain HTTP; the optional Playwright tier
#          is async and is only reached if a `page` is supplied AND tiers 1-2
#          both failed.
# Arguments:
#           url:  the TFRRS results page URL.
#           page: an OPTIONAL Playwright async page for tier 3. If omitted, the
#                 ladder stops after tier 2 (no browser fallback available).
# Output:   the results-page HTML string. Raises RateLimitException on a 429,
#           or CloudflareException if all available tiers returned a block.
async def fetchTFPage(url, page=None):
    # Tier 2 — curl_cffi, also blocking -> thread.
    status, body = await asyncio.to_thread(_tierCurlCffi, url)
    html = _handleVerdict(status, body)
    if html is not None:
        return html

    # Tier 3 — async Playwright, awaited directly (no asyncio.run bridge).
    if page is not None:
        status, body = await _tierPlaywright(page, url)
        html = _handleVerdict(status, body)
        if html is not None:
            return html

    raise CloudflareException(f"TFRRS: all tiers blocked for {url}")
 
 
# _runPlaywrightTier
# Purpose: Bridge the sync orchestrator to the async Playwright tier. Runs the
#          coroutine to completion and returns its (status, html). Kept in its
#          own helper so the sync/async seam is in ONE obvious place rather than
#          smeared through fetchTFPage.
#
#          IMPORTANT: this uses asyncio.run, which creates a NEW event loop, so
#          it must NOT be called from inside an already-running loop. If you ever
#          drive TFRRS from within the anet async launcher, call the async tier
#          directly there instead (await _tierPlaywright(page, url)) rather than
#          going through this sync wrapper. For a standalone sync TFRRS run
#          (the chosen model), asyncio.run is correct.
# Arguments:
#           page, url: as for _tierPlaywright.
# Output:   (status, html).
def _runPlaywrightTier(page, url):
    import asyncio
    return asyncio.run(_tierPlaywright(page, url))