# GENERATED by adjudicate_regressions.py -- repairs that
# DIFFER from the live corrections.py values. No-ops are
# filtered out; see the console census for how many.
_DISTANCE_OVERRIDES_ADDITIONS = {
}
