# GENERATED by adjudicate_regressions.py -- repairs that
# MOVE THE EFFECTIVE DISTANCE. Verdicts that merely restate
# what the ruler already used are filtered as no-ops; see the
# console census for how many.
_DISTANCE_OVERRIDES_ADDITIONS = {
    (4024, 0): 6000.0,  # REFUTED: field (UNIFORM_NEG, iqr=9.1 < 10.4) moved as ONE factor against stored 4748; draft 6000 passes physics
    (14365, 0): 4000.0,  # REFUTED: field (UNIFORM_NEG, iqr=9.0 < 10.4) moved as ONE factor against stored 3200; draft 4000 passes physics
    (19358, 1): 6437.0,  # REFUTED: field (UNIFORM_NEG, iqr=8.4 < 10.4) moved as ONE factor against stored 5000; draft 6437 passes physics
    (80583, 319210): 3200.0,  # REFUTED: field (UNIFORM_NEG, iqr=10.3 < 10.4) moved as ONE factor against stored 2400; draft 3200 passes physics
    (178848, 731333): 4000.0,  # REFUTED: field (UNIFORM_NEG, iqr=7.8 < 10.4) moved as ONE factor against stored 3000; draft 4000 passes physics
    (232109, 926316): 3000.0,  # REFUTED: field (UNIFORM_NEG, iqr=5.5 < 10.4) moved as ONE factor against stored 2500; draft 3000 passes physics
}
